"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _landing_hero from './landing-hero.bones.json'
import _landing_mockup from './landing-mockup.bones.json'
import _landing_features from './landing-features.bones.json'
import _landing_status_demo from './landing-status-demo.bones.json'

registerBones({
  "landing-hero": _landing_hero,
  "landing-mockup": _landing_mockup,
  "landing-features": _landing_features,
  "landing-status-demo": _landing_status_demo,
})
